name: build
on: [push, pull_request]
jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
      id: go

    - name: Check out code 
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
            go mod download
    - name: Build
      run: |
            go build ./...